#!/usr/bin/env python3

import argparse
import glob
import os


def camel(snake_str: str):
    first, *others = snake_str.split('_')
    return ''.join([first.title(), *map(str.title, others)])


def main():
    parser = argparse.ArgumentParser('gen_resolvers')
    parser.add_argument(
        'resolvers',
        type=str,
        help="location of the resolver directory (usually src/resolvers)")

    args = parser.parse_args()
    resolvers: str = args.resolvers
    files = [
        file[len(resolvers):] for file in sorted(
            glob.glob(f'{resolvers}/**/*_resolver.ts', recursive=True))
        if '__tests__' not in file
    ]

    print("// AUTOGENERATED FROM scripts/make_resolvers.py DO NOT MODIFY")
    for file in files:
        basename = os.path.basename(file)
        print(f'import {{ {camel(basename[:-3])} }} from ".{file[:-3]}";')

    print("")
    print('export const ALL_RESOLVERS = [')
    for file in files:
        basename = os.path.basename(file)
        print(f'    {camel(basename[:-3])},')
    print('];')


if __name__ == "__main__":
    main()
