// AUTOGENERATED FROM scripts/make_entities.py DO NOT MODIFY
import { Probe } from "./probe";
import { Rate } from "./rate";
import { Recipe } from "./recipe";
import { Trace } from "./trace/trace";
import { TraceLog } from "./trace/trace_log";
import { TraceLogStatus } from "./trace/trace_log_status";
import { TraceState } from "./trace/trace_state";
import { User } from "./user";

export const ALL_ENTITIES = [
    Probe,
    Rate,
    Recipe,
    Trace,
    TraceLog,
    TraceLogStatus,
    TraceState,
    User,
    // placeholder to prevent prettier from turning array into one line
];
