// AUTOGENERATED FROM scripts/make_entities.py DO NOT MODIFY
import { Class } from "./code/class";
import { File } from "./code/file";
import { Function } from "./code/function";
import { Module } from "./code/module";
import { Probe } from "./probe";
import { Rate } from "./rate";
import { Recipe } from "./recipe";
import { Trace } from "./trace/trace";
import { TraceFailure } from "./trace/trace_failure";
import { TraceLog } from "./trace/trace_log";
import { TraceLogStatus } from "./trace/trace_log_status";
import { TraceSet } from "./trace/trace_set";
import { User } from "./user";

// export all entities written inside a list
export const ALL_ENTITIES = [
    Class,
    File,
    Function,
    Module,
    Probe,
    Rate,
    Recipe,
    Trace,
    TraceFailure,
    TraceLog,
    TraceLogStatus,
    TraceSet,
    User,
];

// re-export all entities for easy importing
// prettier-ignore
export {
    Class,
    File,
    Function,
    Module,
    Probe,
    Rate,
    Recipe,
    Trace,
    TraceFailure,
    TraceLog,
    TraceLogStatus,
    TraceSet,
    User,
};
