// AUTOGENERATED FROM scripts/make_entities.py DO NOT MODIFY
import { Probe } from "./probe";
import { Rate } from "./rate";
import { Recipe } from "./recipe";
import { Trace } from "./trace";
import { User } from "./user";

export const ALL_ENTITIES = [
    Probe,
    Rate,
    Recipe,
    Trace,
    User,
    // placeholder to prevent prettier from turning array into one line
];
