// AUTOGENERATED FROM scripts/make_resolvers.py DO NOT MODIFY
import { ProbeResolver } from "./probe_resolver";
import { RateResolver } from "./rate_resolver";
import { RecipeResolver } from "./recipe_resolver";
import { TraceResolver } from "./trace_resolver";
import { TraceSetResolver } from "./trace_set_resolver";
import { UserResolver } from "./user_resolver";

export const ALL_RESOLVERS = [
    ProbeResolver,
    RateResolver,
    RecipeResolver,
    TraceResolver,
    TraceSetResolver,
    UserResolver,
];
